language: julia
julia:
    - 1.0.5
    - 1.1.1
    - 1.2.0
    - 1.3.1
    - 1.4.2
    - 1.5.4
    - 1.6.1
    - nightly
#    - 0.4.7
#    - 0.6.4
#    - 0.7.0

matrix:
    allow_failures:
        - julia: nightly
#        - julia: 0.7.0
#        - julia: 0.6.4
#        - julia: 0.4.7

os:
    - linux
#    - osx
#    - windows

notifications:
    email: false

codecov: true
coveralls: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip

after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("MaxPlus")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';

